apiVersion: v1beta1
kind: AgentConfig
metadata:
 name: openshiftnonprod-virt
rendezvousIP: 10.186.27.11
additionalNTPSources:
  - #from customer
  - #from customer
  - #from customer
  - #from customer

hosts:
 - hostname: 
   role: master
   rootDeviceHints:
     deviceName: "/dev/sdb" #From Live ISO
   interfaces:
   - name: #name of interface-1 from Live ISO
     macAddress: 00:25:B5:23:AA:88
   - name: #name of interface-2 from Live ISO
     macAddress: 00:25:B5:23:BB:88
   networkConfig:
      interfaces:
        - name: bond0.2878
          type: vlan
          state: up
          vlan:
            base-iface: bond0
            id: 2878
          ipv4:
            enabled: true
            address:
              - ip: 10.186.27.11
                prefix-length: 24
            dhcp: false
        - name: bond0
          type: bond
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: "active-active"
            options:
              miimon: "150"
            port:
              - #interface-1
              - #interface-2
      dns-resolver:
        config:
          server:
                - #from customer
                - #from customer
      routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 10.186.27.254
              next-hop-interface: bond0.2878
              table-id: 254


 - hostname: 
   role: master
   rootDeviceHints:
     deviceName: "/dev/sdb" #From Live ISO
   interfaces:
   - name: #name of interface-1 from Live ISO
     macAddress: 00:25:B5:23:AA:43
   - name: #name of interface-2 from Live ISO
     macAddress: 00:25:B5:23:BB:42
   networkConfig:
      interfaces:
        - name: bond0.2878
          type: vlan
          state: up
          vlan:
            base-iface: bond0
            id: #get it from the Live ISO or provided by customer
          ipv4:
            enabled: true
            address:
              - ip: 10.186.27.12
                prefix-length: 24
            dhcp: false
        - name: bond0
          type: bond
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: "active-active"
            options:
              miimon: "150"
            port:
              - #interface-1
              - #interface-2
      dns-resolver:
        config:
          server:
                - #from customer
                - #from customer
      routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 10.186.27.254
              next-hop-interface: bond0.(#vlan id)
              table-id: 254

 - hostname: 
   role: master
   rootDeviceHints:
     deviceName: "/dev/sdb" #From Live ISO
   interfaces:
   - name: #name of interface-1 from Live ISO
     macAddress: 00:25:B5:23:AA:04
   - name: #name of interface-2 from Live ISO
     macAddress: 00:25:B5:23:BB:04
   networkConfig:
      interfaces:
        - name: bond0.(#vlan id)
          type: vlan
          state: up
          vlan:
            base-iface: bond0
            id: #get it from the Live ISO or provided by customer
          ipv4:
            enabled: true
            address:
              - ip: 10.186.27.13
                prefix-length: 24
            dhcp: false
        - name: bond0
          type: bond
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: "active-active"
            options:
              miimon: "150"
            port:
              - #interface-1
              - #interface-2
      dns-resolver:
        config:
          server:
                - #from customer
                - #from customer
      routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 10.186.27.254
              next-hop-interface: bond0.(#vlan id)
              table-id: 254
