#"ABI Compact Cluster 3 Masters 'Schedulable' and 0 Workers"
apiVersion: v1
baseDomain: openshiftnonprod-virt.staff.banquemisr.bank
metadata:
  name: openshiftnonprod-virt

compute:
  - name: worker
    replicas: 0

controlPlane:
  name: master
  replicas: 3

networking:

  clusterNetwork:
    # This is the Cluster Network CIDR and Host Prefix.
    - cidr: 10.234.0.0/16
      hostPrefix: 21 #controls how many Pod IPs are carved out per node from the larger CIDR.

  machineNetwork:
    # This is the Cluster Machine Network CIDR "The rendezvousIP, apiVIP, and ingressVIP".
    - cidr: 10.186.27.9/24

  serviceNetwork:
    # This is the Cluster Services Network "ClusterIP, NodePort, LoadBalancer".
    - 10.233.0.0/16

  networkType: OVNKubernetes

platform:
  baremetal:
    apiVIPs:
      - 10.186.27.7
    ingressVIPs:
      - 10.186.27.8

pullSecret: '<your-pull-secret -- get it from https://cloud.redhat.com/openshift/install/pull-secret>'

sshKey: '<contents of ~/.ssh/id_ed25519.pub>'