apiVersion: v1beta1
kind: AgentConfig
metadata:
 name: ocp-prod
rendezvousIP: 10.51.201.20
additionalNTPSources:
  - 10.0.2.99
  - 10.0.2.100

hosts:
 - hostname: dai-cldp01
   role: master
   rootDeviceHints:
     deviceName: "/dev/sdb"
   interfaces:
   - name: ens35f0np0
     macAddress: 8c:84:74:5d:36:00
   - name: ens33f0np0
     macAddress: 8c:84:74:5d:36:01
   networkConfig:
      interfaces:
        - name: bond0.1201
          type: vlan
          state: up
          vlan:
            base-iface: bond0
            id: 1201
          ipv4:
            enabled: true
            address:
              - ip: 10.51.201.20
                prefix-length: 24
            dhcp: false
        - name: bond0
          type: bond
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: "active-active"
            options:
              miimon: "150"
            port:
              - eno12399np0
              - eno12409np0
      dns-resolver:
        config:
          server:
                - 10.0.2.99
                - 10.0.2.100
      routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 10.51.201.1
              next-hop-interface: bond0
              table-id: 254


